### ISSUE TITLE
Rod issue with the fishing rod

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/EcoSkills#34]
**Describe the bug**
When using a rod each time you will have an exp gain message, some items I have from ecoitems has cooldowns in the actionbar and this is making it not visible. The issue is that I shouldn't see an exp gain message when just spamming right click with my rod / it's not even in water

**To Reproduce**
1. Grab a fishing rod
2. Spam right click

**Expected behavior**
I shouldn't see a exp gain message (it's saying I got +0xp)

**Screenshots**
https://gyazo.com/6a29bcdd0d93fbc8ac7d29fad97c45f1

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
Eco: 6.20.4
EcoSkills: 1.20.9

**Additional context**
None atm

**Comment by WillFP** [comment]
Fixed in latest
