### ISSUE TITLE
Double drop - doesnt work

### ISSUE THREAD

**Issue by Aides123** [Auxilor/EcoSkills#36]
**Describe the bug**
The multiplier with skill lumberjack does not work.
I gave myself 200% to triple cut wood but after few minutes it didn't even add 1 extra wood.

**To Reproduce**
Just cut down the tress ;3

**Expected behavior**
Expect it to work as described i.e. add wood by chance

**Screenshots**
XXX

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
- This server is running Pufferfish version git-Pufferfish-20 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b9556fd on HEAD)
Received invalid status code (404) from server.
Previous version: git-Pufferfish-8 (MC: 1.17.1)
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
- ![image](https://user-images.githubusercontent.com/23367220/151717536-f07ac3aa-8f85-46e4-9140-0947c1a0c9de.png)

**Comment by Aides123** [comment]
Also farming double drop dont work

**Comment by mercury55554** [comment]
+

**Comment by Aides123** [comment]
Does anyone plan to fix this? Because this bug was reported over 10 days ago on discord and was already known

**Comment by WillFP** [comment]
Fixed in latest
