### ISSUE TITLE
Player Health Adds more health than specified in config.yml

### ISSUE THREAD

**Issue by Heinicke** [Auxilor/EcoSkills#44]
**Describe the bug**
Player health scales much higher than just 1 hp even when set to 1 in config

**To Reproduce**
Use Default Config
Type /ecoskills give health 15

This will result in the player having over 400 hp rather than the player having +15 hp

**Expected behavior**
The HP that adds is the same as what is set in the config

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
This server is running Paper version git-Paper-187 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0cc2503)
You are running the latest version
Previous version: git-Paper-186 (MC: 1.18.1)

- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
[20:55:04 INFO]: eco version 6.24.1
[20:55:04 INFO]: Website: willfp.com
[20:55:04 INFO]: Author: Auxilor

[20:54:45 INFO]: EcoSkills version 1.20.16
[20:54:45 INFO]: Website: willfp.com
[20:54:45 INFO]: Author: Auxilor

**Comment by WillFP** [comment]
Fixed in latest
