### ISSUE TITLE
Skills GUI

### ISSUE THREAD

**Issue by rosiejane** [Auxilor/EcoSkills#46]
**Is your feature request related to a problem? Please describe.**
If the numbers above 64 don't chance due to a minecraft limitation, would it instead be possible to disable all of the WHITE numbers from showing up and just have plain glass panes such as the first one? (level 1) 

**Describe the solution you'd like**
Just plain glass paines with no white numbers. 

**Describe alternatives you've considered**
N/A

**Additional context**
![pa](https://user-images.githubusercontent.com/54243352/153719162-3436e802-ab8f-45ab-a630-f22d8dcbb159.png)

**Comment by WillFP** [comment]
Already an option: level-gui.level-as-amount

**Comment by rosiejane** [comment]
> level-gui

@WillFP 

Hello. Where is this option please as i dont see it.

The only option i see is

level-gui:
  rows: 6

Thank you
