### ISSUE TITLE
Skill_xp_multiplier not working for Ecoskills

### ISSUE THREAD

**Issue by Miryex** [Auxilor/EcoSkills#47]
The Skill XP multiplier doesnt work with ecoskills, maybe with mcmmo too. 

**To Reproduce**
1. Add Skill xp multiplier to a talisman
2. Try the skill
3. Skill xp doesnt get added

**Expected behavior**
It should multiply the Skill xp

**Server Information (please complete the following information):**
- Paper version git-Paper-205 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 36a1650)
- eco-6.25.2-all, Talismans v5.25.5, EcoSkills v1.20.22

My Layout:
  effects:
  - id: skill_xp_multiplier
    args:
      multiplier: 1.05
      skill: woodcutting

**Comment by WillFP** [comment]
should be skills: [woodcutting]

**Comment by Miryex** [comment]
![image](https://user-images.githubusercontent.com/93775214/155723063-f713806c-d5e4-4ca3-9459-1ba1ee4e0597.png)
Doesnt seem to work for me :/
