### ISSUE TITLE
PlaceholderAPI

### ISSUE THREAD

**Issue by NecroSeigen** [Auxilor/EcoSkills#48]
The menu is good, but I would like to push it further, so I made a new one with the command panel plugin which is made for that. However, I realized that the PlaceholderAPI %percentage_progress%, %current_xp%& and %required_xp% (from the config.yml) do not exist. 
It's not practical for displaying skill experience, so for now I'm doing without, but an update that adds them could be very cool.

**Comment by WillFP** [comment]
Coming in next update
