### ISSUE TITLE
Action Bar xp gain

### ISSUE THREAD

**Issue by NecroSeigen** [Auxilor/EcoSkills#59]
**Is your feature request related to a problem? Please describe.**
This is a problem for people who use the action bar to display health etc. Let me explain, when a player gains experience on a skill, a new action bar appears without the knowledge of the constant action bar. The problem is that when a player takes damage, they no longer see their health. 

**Describe the solution you'd like**
So I propose to add a feature like on Hypixel's SkyBloc, when a player receives skill experience, that experience is displayed in the constant action bar, see the image below.

**Describe alternatives you've considered**
Make either a PlaceholderAPI like %ecoskills_xp_gain% or just a line in the config.yml, I don't have much idea, I hope you understand me. 

**Additional context**
![unknown](https://user-images.githubusercontent.com/81390182/158847390-81d5aa26-aa05-4758-85e8-805c8e43b3dd.png)

**Comment by WillFP** [comment]
You can already do that, just put the health/mana/whatever in the action bar format
