### ISSUE TITLE
EcoEnchants removes lore from another plugins items (AutoShulker)

### ISSUE THREAD

**Issue by RebelMythik** [Auxilor/EcoSkills#60]
**Describe the bug**

**To Reproduce**
1. Craft AutoShulker
2. Place it on the ground
3. Break it and lore is gone and shulker is broken

**Expected behavior**

**Screenshots**
With EcoEnchants
![image](https://user-images.githubusercontent.com/50276986/159058902-2162a299-9768-4aba-ae4c-003d988d3fd4.png)

Without EcoEnchants
![image](https://user-images.githubusercontent.com/50276986/159058870-50cec065-c661-43c7-936d-66b1c115b141.png)

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
Eco Version: 6.29.1
EcoEnchants version: 8.49.3

**Comment by WillFP** [comment]
Fixed in latest autoshulker
