### ISSUE TITLE
Serrated Strikes hitting players with PvP toggled off.

### ISSUE THREAD

**Issue by dsevvv** [Auxilor/EcoSkills#61]
**Describe the bug**
So I let players toggle pvp while they are in our spawn hub. I use DeluxeCombat to control this functionality.

If players have pvptoggled off, they cannot be hit directly by a player, but if the player's serrated strikes ability procs, the bleed will still apply and do damage to the target.

**To Reproduce**
Download DeluxeCombat. 
Turn on the feature to allow players to toggle pvp with the "togglepvp" command.
Hit another player that has pvp toggled off.
See that you will apply serrated strikes bleed.

**Expected behavior**
I do not want the bleed to apply if a player has pvp toggled off for obvious reasons.

**Screenshots**
I don't believe any are needed to understand this issue.

**Server Information (please complete the following information):**
- Version: This server is running Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)
You are running the latest version
Previous version: git-Paper-207 (MC: 1.18.1)
- Version of plugin and eco: eco 6.28.3, ecoskills: 1.20.29

**Additional context**
I don't believe any extra context is needed.

**Comment by WillFP** [comment]
Fix coming in next version
