### ISSUE TITLE
Skills Reset after Server Restart

### ISSUE THREAD

**Issue by bsamemes** [Auxilor/EcoSkills#65]
**Describe the bug**
After daily server restarts, players’ skills and progress reset.

**To Reproduce**
1. Give yourself enough skill xp to level up a skill
2. Disconnect
3. Restart server
4. Join back, skills will be reset

**Expected behavior**
Player skill progress should be saved and not reset.

**Screenshots**

**Server Information (please complete the following information):**
- Version: Paper 1.18.2 #267
- Version of plugin and eco: EcoSkills 1.21.2, Eco 6.29.2

**Additional context**

**Comment by Plxsi** [comment]
I have exactly the same problem! This is a massive bug!

**Comment by WillFP** [comment]
Closed as duplicate

**Comment by bsamemes** [comment]
Adding to this from looking into it further. Updated Eco to latest version, its actually that the skills reset on player rejoins, not server restarts.
