### ISSUE TITLE
ECOSKILL RESET BUG!

### ISSUE THREAD

**Issue by Plxsi** [Auxilor/EcoSkills#66]
**Describe the bug**
If you disconnect from the server skill reset!

**To Reproduce**
If you disconnect from the server skill reset!

**Expected behavior**
For the skills to save.

**Screenshots**
N/A

**Server Information (please complete the following information):**
- Version: 1.18.1
- Version of plugin and eco! Lastest

**Additional context**
N/A

**Comment by WillFP** [comment]
Closed as duplicate
