### ISSUE TITLE
Skills reset

### ISSUE THREAD

**Issue by SingleHunter** [Auxilor/EcoSkills#70]
Describe the bug
All player skills are reset when you rejoin into the server. This does not apply only to the server operators

To Reproduce
1. Log out of the server
2. Log in to the server
3. the skills will be reset

Expected behavior
save the skills 

Server Information (please complete the following information):
- Version:  This server is running Pufferfish version git-Pufferfish-47 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: a786526 on HEAD)
- Version of plugin and eco: Latest 

Additional context
I also see this error in the console:
https://pastebin.com/gpSanbX8
This bug with resetting skills also occurs on versions 1.18.1 and 1.18.2, on the server core Purpur and Pufferfish

**Comment by WillFP** [comment]
Should be fixed in latest
