### ISSUE TITLE
Option to delete skills

### ISSUE THREAD

**Issue by Scrulius** [Auxilor/EcoSkills#78]
Hello @WillFP !

I love EcoSkills but I have found a problem, I can't delete/disable the default skills

An option to disable/delete the skills would be awesome and necessary!

Best regards ^^

Discord: Melonzio#9859

**Comment by iSeitan** [comment]
An awesome idea!

**Comment by Bounser** [comment]
Both an option to delete and to create new skills would be nice. But it is clear that one to remove  skills (that do not fit in the server) is necessary.

**Comment by Scrulius** [comment]
> Both an option to delete and to create new skills would be nice. But it is clear that one to remove skills (that do not fit in the server) is necessary.

I just need to disable them, putting an option like in EcoEnchants is enough, such as "enabled: false"

**Comment by Scrulius** [comment]
> Both an option to delete and to create new skills would be nice. But it is clear that one to remove skills (that do not fit in the server) is necessary.

I just need to disable them, putting an option like in EcoEnchants is enough, such as "enabled: false"

**Comment by WillFP** [comment]
yep will add

**Comment by WillFP** [comment]
Added in 1.36.0
