### ISSUE TITLE
Custom GUI problem

### ISSUE THREAD

**Issue by Dani3lFTW** [Auxilor/EcoSkills#80]
Hi, i'm, working on a custom textured server and i have a problem with the skills gui.
When i try to set the custom gui (it must be set in the gui name) apparently the name of the skill also changes.
Can it be solved somehow? 

https://cdn.discordapp.com/attachments/878703088763043950/978596877694038087/unknown.png

**Comment by Dani3lFTW** [comment]
Any updates?

**Comment by WillFP** [comment]
What have you put in config?

**Comment by Dani3lFTW** [comment]
This: https://prnt.sc/gRS8AzzO0k77

That being the name of the skill, the problem is that the plugin does not give you the ability to set what you want for the gui name, but automatically sets the name of the skill.

**Comment by Booquefius** [comment]
Can you please send the full config?

**Comment by WillFP** [comment]
Add a name: option under your GUI config
