### ISSUE TITLE
EcoSkills Mythicmobs Integration

### ISSUE THREAD

**Issue by xVoidWave** [Auxilor/EcoSkills#82]
**Is your feature request related to a problem? Please describe.**
Currently EcoSkills lacks some crucial integration into MythicMobs, the most popular and modular custom mob/boss creator on the market (sorry ecobosses :3). People really need to be able to make skills pertaining to a specific mob/mob faction from Mythicmobs.

**Describe the solution you'd like**
Add a filter/condition to effects so an effect, for example, can only trigger if the target is a specific mob (based on mythicmobs internal mob ID system) or if the target is in a specific mythicmobs faction. Links to important info at bottom.

**Important Links:**
https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/Mobs
https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/Mobs/Factions

**Comment by Scrulius** [comment]
It is very necessary for RPG servers, I just need to be able to configure the XP given by the MythicMobs in the combat skill.

**Comment by Dani3lFTW** [comment]
it would be great :3 i need it too

**Comment by WillFP** [comment]
Use `mythicmobs:<id>` in the entities filter
